meta_product_name: "Karl"
meta_title: "Karl - Arrêtez de vous faire rouler"
meta_description: "Karl vous permet de générer l'annonce de votre voiture pour ensuite
l'expédier sur les principaux sites de vente à particulier"
meta_image: "Logo_Meta.png"
